services:
  backend:
    image: 749929394992.dkr.ecr.us-east-1.amazonaws.com/adeife/todo-backend:v4
    container_name: todo-backend-server
    ports:
      - "8094:8094"
    environment:
      - PORT=8094
      - MONGO_URI=mongodb://mongo:27017/todoapp
    depends_on:
      - mongo

  client:
    image: 749929394992.dkr.ecr.us-east-1.amazonaws.com/adeife/todo-client:v4
    container_name: todo-client-server
    ports:
      - "8095:8095"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8094}
    depends_on:
      - backend

  mongo:
    image: mongo:7.0
    container_name: todo-mongo
    ports:
      - "27017:27017"
