name: Deploy Application

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform"]
    types:
        - completed

env:
  AWS_REGION: us-east-1


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
        id-token: write
        contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::749929394992:role/github-actions-role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Get EC2 IP from Terraform state
        id: get_ip
        run: |
          cd aws-infra
          terraform init --input=false -no-color
          APP_IP=$(terraform output -raw todo_public_ip 2>/dev/null | head -n 1 | tr -d '\r')
          echo "APP_IP=$APP_IP" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Client Image
        working-directory: ./Todo-app/client
        run: |
          docker build -t adeife/todo-client:v1 .
          docker tag adeife/todo-client:v1 749929394992.dkr.ecr.us-east-1.amazonaws.com/adeife/todo-client:v1
          docker push 749929394992.dkr.ecr.us-east-1.amazonaws.com/adeife/todo-client:v1

      - name: Build and Push Backend Image
        working-directory: ./Todo-app/backend
        run: |
          docker build -t adeife/todo-backend:v1 .
          docker tag adeife/todo-backend:v1 749929394992.dkr.ecr.us-east-1.amazonaws.com/adeife/todo-backend:v1
          docker push 749929394992.dkr.ecr.us-east-1.amazonaws.com/adeife/todo-backend:v1

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEMO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Get ECR login password
        id: ecr-password
        run: |
          ECR_PASSWORD=$(aws ecr get-login-password --region ${{ env.AWS_REGION }})
          echo "ECR_PASSWORD=$ECR_PASSWORD" >> $GITHUB_ENV

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.APP_IP }}
          username: ec2-user
          key: ${{ secrets.DEMO_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ec2-user/app"

      - name: Deploy App to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.APP_IP }}
          username: ec2-user
          key: ${{ secrets.DEMO_SSH_KEY }}
          envs: ECR_PASSWORD, AWS_REGION
          script: |
            echo "Successfully connected to instance"
            sudo yum update -y || true

            sudo amazon-linux-extras enable docker
            sudo yum install -y docker || true

            sudo systemctl start docker
            sudo systemctl enable docker

            sudo usermod -aG docker ec2-user || true

            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

            sudo chmod +x /usr/local/bin/docker-compose
            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose || true

            echo "$ECR_PASSWORD" |sudo docker login --username AWS --password-stdin 749929394992.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

            cd /home/ec2-user/app
            export VITE_API_URL=http://${{ env.EC2_IP }}:8094

            sudo docker-compose down || true
            sudo docker-compose pull
            sudo docker-compose up -d --build

            echo "Todo App deployed successfully"